name: fitbattles
description: "Fit Battles is a dynamic mobile application designed to encourage users to engage in fitness challenges and track their progress. The app allows users to create and join fitness battles with friends, compete in various activities, and earn rewards for their achievements. Leveraging Firebase services, Fit Battles provides real-time updates, user authentication, and cloud storage for user-generated content.

Key features include:

- **User Authentication**: Secure sign-up and login through Firebase Authentication, ensuring a personalized experience.
- **Challenge Creation**: Users can create and customize fitness challenges to motivate themselves and their friends.
- **Progress Tracking**: Track workouts, monitor progress, and visualize achievements with user-friendly dashboards.
- **Real-Time Updates**: Stay connected with friends and receive notifications about their fitness activities using Firebase Cloud Messaging.
- **Media Sharing**: Upload and share workout photos and videos via Firebase Storage.

Fit Battles aims to foster a supportive fitness community while making the journey toward a healthier lifestyle engaging and fun."
publish_to: '' # Leave empty or remove for a private package

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.2.0
  firebase_storage: ^12.0.0
  firebase_messaging: ^15.1.2
  http: ^1.2.2
  flutter_local_notifications: ^17.2.3
  provider: ^6.0.0
  image_picker: ^1.1.2
  health: ^11.0.0
  dart_format: ^1.1.20
  firebase_analytics: ^11.3.2
  firebase_database: any
  firebase_ui_database: ^1.4.4
  logger: ^1.0.0
  shared_preferences: ^2.3.2
  geolocator: ^13.0.1
  cupertino_icons: ^1.0.8
  getwidget: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logo2.png
    - assets/images/placeholder_avatar.png
    - assets/images/bob.png
    - assets/images/charlie.png
    - assets/images/hannah.png
    - assets/images/ian.png
    - assets/images/fiona.png
    - assets/images/george.png
    - assets/images/ethan.png
    - assets/images/diana.png
    - assets/images/alice.png
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf